const fs=require('fs');
const p='src/lib/actions/running_actions.ts';
let c=fs.readFileSync(p,'utf8');
c = c.replace(/target_description,/g, 'title, target_description,');
c = c.replace(/target_description: s\.description,/g, 'title: s.title, target_description: s.description,');
c = c.replace(/target_description: b\.target_description,/g, 'title: b.title, target_description: b.target_description,');
c = c.replace(/target_description: tw\.target_description,/g, 'title: tw.title, target_description: tw.target_description,');
c = c.replace(/target_description: validatedFields\.data\.targetDescription,/g, 'title: validatedFields.data.title, target_description: validatedFields.data.targetDescription,');
c = c.replace(/targetDescription: formData\.get\('targetDescription'\) \|\| undefined,/g, 'title: formData.get(''title'') || undefined, targetDescription: formData.get(''targetDescription'') || undefined,');
c = c.replace(/targetDescription: formData\.get\("targetDescription"\) \|\| undefined,/g, 'title: formData.get("title") || undefined, targetDescription: formData.get("targetDescription") || undefined,');
c = c.replace(/targetDescription: formData\.get\("targetDescription"\),/g, 'title: formData.get("title") || undefined, targetDescription: formData.get("targetDescription"),');
c = c.replace(/targetDescription: b\.targetDescription,/g, 'title: b.title, targetDescription: b.targetDescription,');
c = c.replace(/const targetDescription = formData\.get\("description"\) as string;/g, 'const title = formData.get("title") as string;\n  const targetDescription = formData.get("description") as string;');
c = c.replace(/target_description: targetDescription,/g, 'title: title,\n    target_description: targetDescription,');
c = c.replace(/targetDescription: string;/g, 'title?: string | null;\n    targetDescription: string;');
c = c.replace(/target_description: string;/g, 'title?: string | null;\n  target_description: string;');
c = c.replace(/id,\n      scheduled_date,\n      completed_at,\n      target_description,/g, 'id,\n      scheduled_date,\n      completed_at,\n      title,\n      target_description,');
fs.writeFileSync(p,c,'utf8');
